### ISSUE TITLE
Title cut off when the browser page is on smaller screen / half screen

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-filemanager#22]
Steps to reproduce:

1. Create some folders with long titles
2. Change the browser size - make the browser page half the screen
3. Observe the titles

Expected results: The titles are readable no matter the size of the browser page.

Actual results: The titles are cut off.

Environment: Windows 10, XWiki 11.3.6 with MySQL 5.7 and Edge 18

![Full name Full Screen](https://user-images.githubusercontent.com/40691112/69244183-2d91d080-0bad-11ea-9f51-a1df5834f324.jpg)

![Name Cut Off](https://user-images.githubusercontent.com/40691112/69244194-31255780-0bad-11ea-9f12-bcff7c63ca10.jpg)

**Comment by petrenkonikita112263** [comment]
Can't reproduce issue on latest version of XWiki 15.9 and FileManager (Pro) 2.6. Because it's not a bug, there's a slider between FileManagerTree and LiveData table, using it user can change width of column.

![msedge_k3mMZ9zXHY](https://github.com/xwikisas/application-filemanager/assets/56109799/9331d037-e600-4528-9e5d-79b9bbc1451b)

OMV, can be closed.

**Comment by snazare** [comment]
I confirm on 14.10.18 there is the same slider that allows users to add more space on the left panel.
