### ISSUE TITLE
File Manager Pro does not respect the naming strategy set at wiki level when saving pages

### ISSUE THREAD

**Issue by ilieandriuta** [xwikisas/application-filemanager#36]
STEPS TO REPRODUCE

Tested on XWiki 12.6.2 with File Manager Pro 2.2.11

1. Login as Admin
2. Go to Administer Wiki > Editing > Name Strategies
3. Select 'Preformatted names (no accents, no space, no special characters)' as Current Naming Strategy, 'Transform Names Automatically' as Enabled
4. Go to File Manager's home page
5. Right click on File Manager > New Folder and add a folder with a name containing spaces, an accent and a special character (e.g. Té stΦéd)
6. Hit 'Enter'

EXPECTED RESULTS

The page is saved according to the naming strategy selected at wiki level (e.g. Te-st-ed).

ACTUAL RESULTS

The page is saved without any transformation.

![File Manager - Strategy not respected](https://github.com/xwikisas/application-filemanager/assets/32512703/4f81807c-25a3-4282-95f3-778d40bba80f)

Environment: Windows 10 Pro 64bit, Edge 85, using a local instance of XWiki 12.6.2 on Oracle 19c, Tomcat 9.0.37

**Comment by ane-gabriela** [comment]
Reproducing on XWiki 14.10.15 with File Manager Application (Pro) 2.6, Chrome 117

![Tested](https://github.com/xwikisas/application-filemanager/assets/40691112/80272a57-c70e-43d9-9af3-a76ae90d666c)

**Comment by petrenkonikita112263** [comment]
@ilieandriuta and @ane-gabriela are you sure about the configuration of Name strategies on XWiki? Because if I enabled *Validate names before saving* by default it's disabled, the FileManager (Pro) won't save the folder with name that has mentioned characters. Tested on 15.9 XWiki, and with enabled validation saving won't happen. Without it saving works but transforming doesn't work.

![msedge_xWJdbQvr8F](https://github.com/xwikisas/application-filemanager/assets/56109799/ee2e093d-0a1a-44af-8686-3fe27b5bda17)

**Comment by ilieandriuta** [comment]
> @ilieandriuta and @ane-gabriela are you sure about the configuration of Name strategies on XWiki? Because if I enabled _Validate names before saving_ by default it's disabled, the FileManager (Pro) won't save the folder with name that has mentioned characters. Tested on 15.9 XWiki, and with enabled validation saving won't happen. Without it saving works but transforming doesn't work.

@petrenkonikita112263 I've tested and the issue reproduces also on XWiki 15.10 following the steps from the ticket above. 

The point of the issue is that the Name Strategy set at wiki level is not respected, i.e. the page is saved without any transformation. 

The fact that after enabling the "Validate names before saving" option the page is not saved at all it's a side-case that should also be addressed (maybe along with fixing this issue), but just following the steps described in the ticket lead to issue's reproduction.

**Comment by petrenkonikita112263** [comment]
I did new tests on recent version XWiki 15.10, and OMV it's not issue of File Manager (Pro), because you can reproduce it during the creation page. Then it should be closed and reported as product issue of XWiki

![image](https://github.com/xwikisas/application-filemanager/assets/56109799/12c2ee93-1e9f-4ff4-8484-8cd904c0cf05)

my URL of page `http://localhost:8080/xwiki/bin/view/XWiki/T%C3%A9%20st%CE%A6%C3%A9d/#Information`

And activated option VALIDATE NAMES BEFORE SAVING 
![image](https://github.com/xwikisas/application-filemanager/assets/56109799/a42bcf56-a521-455d-9dd1-31508182abc7)

I assume, if XWiki displays that name isn't valid that page must not be created.

**Comment by ane-gabriela** [comment]
Issue reproducing on Cloud XWiki 1510.8, File Manager Application (Pro) 2.8, Chrome 125, Windows 11
