### ISSUE TITLE
Add thumbnails to images files

### ISSUE THREAD

**Issue by js-ddev** [xwikisas/application-filemanager#6]
For example in the screenshot below, Friday.jpg and Luf.jpg icons would be a miniature of the image instead of the image filetype icon.
![livetable](https://user-images.githubusercontent.com/27762774/47793335-520ad880-dd1e-11e8-8004-7a53fa4e5ffd.png)

**Comment by mflorea** [comment]
If we want to add a preview for image attachments, like in the Attachment tab on recent versions of XWiki, then we need to increase the size of the icon. A preview using 16px doesn't help much. I would start with 32px, centering the file name vertically. It would make sense to also increase the user avatar to 32px in this case. And while we're at this, it would also be nice to replace the hard-coded Silk icons with dynamic icon theme.

The icon used on the Attachments tab is generated from Velocity using the [``mimetypeimg``](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-web/src/main/webapp/templates/macros.vm#L435) macro. We cannot use it as is in the File Manager because most of the File Manager UI is written in JavaScript (Angular). But you can check what the [attachment picker](https://github.com/xwiki/xwiki-platform/blob/master/xwiki-platform-core/xwiki-platform-web/src/main/webapp/resources/uicomponents/suggest/suggestAttachments.js#L166) does to have the icon in JavaScript.

On the File Manager side, you need to start from ``FileManagerCode.DriveSheet`` which has a ``file`` Angular directive that controls how files are displayed. You can see there how the Silk icons are hard-coded.
