### ISSUE TITLE
You don't receive a warning message when a large file could not be deleted from File Manager UI

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-filemanager#7]
The issue has been noticed on XE 6.4.8 and it also reproduces on XWiki 10.11.8.

When trying to delete a file equal or larger than 50 MB from the File Manager UI, the page reloads without deleting the selected file.

An improvement for this kind of situations would be to include a warning mentioning that the deletion was not possible and perhaps a workaround like accessing the file page and adding ?viewer=attachments to the URL in order to delete the file from than location directly.

Please see the status log error: https://up1.xwikisas.com/#5kPVukqXjU7ncop7btkFMA

Thank you.

**Comment by AndreeaChi** [comment]
I have tested issue on an instance of XWiki 10.11.8 and the issue still reproduced with large files (around 60MB). 

I used the same workaround: accessing the file page, then adding ?viewer=attachments to the URL of the file page to delete the attached file, and then going back to the File Manager list of documents where now the deletion of that specific file was possible.

**Comment by polx** [comment]
## Analysis
This is not the only problem that can happen when manipulating big files: I also met Out-of-Memory-Errors when uploading a 60M file (that's a bug due to the fact the file-upload's API does not offer stream). The deletion was also causing an OOM as far as I could debug (I got this only once... not so easy since you get an OOM before for the upload).
My current conclusion: Depending on the hard disk quite much any action can generate errors.

## Proposed solution
Could I suggest that we store in the user's session the exceptions that get generated and show them using the [notification widget](https://www.xwiki.org/xwiki/bin/view/Documentation/DevGuide/FrontendResources/XWikiNotifications/) when a subsequent request appears?

**Comment by mflorea** [comment]
@polx AFAIK the delete and upload operations are performed with asynchronous HTTP requests, so you should first make sure that these requests have the proper status code, e.g. 500 if the delete or upload failed on the server. Returning 200 when you get OOM is obviously wrong. Then the next step is to return / display a nice non-technical translated error message that matches the failure from the server.

**Comment by polx** [comment]
But aren't OOM typically yielding timeouts?
I'd prefer to have a parallel channel.

The upload-operation also has a progress bar so that would be the place but I had very often timeouts: Things were blocked at an early stage of the progression.

**Comment by mflorea** [comment]
@polx this issue is about the delete operation. It's good that you are taking the upload operation into account, but let's focus on this issue first. From the description of this issue:

> When trying to delete a file equal or larger than 50 MB from the File Manager UI, the page reloads without deleting the selected file.

my guess is that the File Manager thinks the delete operation succeeded and thus it reloads the files live table, but the file is still there because the operation failed. So again, IMO the first thing to check is the **status** of the delete operation. Is it 200 or 500? If it's 200 then this is definitely a problem on the server side. If the status is 500 then this is a problem on the client side.

**Comment by polx** [comment]
Yes, you were right. It just reloads after done... Whatever happened.
So, I now have a prototype which transmits the error and displays an alert when this error is non-empty. Should it display the error in an alert simply or should I try to use the XWiki notification widget? Should I repeat the exception or just indicate the files that failed to delete?

**Comment by mflorea** [comment]
I would use the XWiki notification widget to show the error message. I'm wondering if we should reload the live table or not. When deleting multiple files some may get deleting and others may fail, so reloading the live table would be good because the user will see the result. Refreshing the live table and preserving the selection (for the files that failed to be deleted) might be the best option.

**Comment by polx** [comment]
This should be fixed by [PR 25](https://github.com/xwikisas/application-filemanager/pull/25).

**Comment by mflorea** [comment]
@polx you closed this by mistake? The PR is still open. Moreover, this issue doesn't have an Assignee and a Milestone set. Would be good to set the proper Labels also. Thanks.

**Comment by polx** [comment]
Pull request #25 is merged.
Thanks to test.

**Comment by polx** [comment]
This issue is now fixed and the release 2.2.11 carries this fix.
Thanks to test.
