### ISSUE TITLE
Add location in the "All Files" section, improvement needed in Recent Files panel also

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-filemanager#8]
When having many folders and adding the same document in some of them, the document appears in the **All Files** section as many times as it was added in separate folders. 
This seems to be confusing for a user that sees the **All Files** section as the file just appears N times with only the "Modified" section Maybe being different if the file was added at a different time.
Would suggest to add a Location column to separate the files.
The **Recent Files** panel would also need an improvement in this case.

![addingsamefilediffrentfolders](https://user-images.githubusercontent.com/40691112/52568680-1cdf4d80-2e18-11e9-9db8-5d2a014b7482.jpg)
![nofilesadded](https://user-images.githubusercontent.com/40691112/52568681-1cdf4d80-2e18-11e9-9b39-7689c7ca5d5d.jpg)

**Comment by oanalavinia** [comment]
@ane-gabriela Do you expect to see only the name of the parent folder, or a reference to its page?
For me, only the name is enough for seeing the difference between files.

**Comment by ane-gabriela** [comment]
Adding also the parent folder would be great, to have a clear a distinction between the files.

**Comment by oanalavinia** [comment]
Added the full path of the file as a 'hint' under the file name for the livetable and as a tooltip for the recent files macro (since it would be to much to make visible the full path in a small panel)

![filemanager_panel](https://user-images.githubusercontent.com/22794181/68277389-c2f27800-0077-11ea-92bf-48a0dfacd3d1.jpg)
![filemanager_tabel](https://user-images.githubusercontent.com/22794181/68277390-c2f27800-0077-11ea-8d6f-a7aad8ff5720.png)
